name = "mytable"
type = "Webpack"
main = "index.js"
compatibility_date = "2023-01-19"
account_id = "4083b2248cb43fc8c9d6284a8e359b1d"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "appI93okOnIYCOyGi"
AIRTABLE_TABLE_NAME = "Table"
FORM_URL = "https://my-profo.vercel.app"
